log_level: info

behavior:
  read_only: false
  autocommit: true

user:
  name: zatan
  password: abc123

listener:
  host: localhost
  port: 3306
  max_connections: 100
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000

performance:
  query_parallelism: null